In [11]:
#Carregando os dados
import pandas as pd
arquivo = pd.read_csv("C:/Users/J/Desktop/Tabelas/wine_dataset.csv")
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [12]:
#Trocando o valor de 0 para 1 
arquivo["style"] = arquivo["style"].replace("red", 0)
arquivo["style"] = arquivo["style"].replace("white", 1)
#Separando as  variÃ¡veis
y = arquivo["style"]
x = arquivo.drop("style", axis = 1)

C:\Users\J\AppData\Local\Temp\ipykernel_26508\123003242.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  arquivo["style"] = arquivo["style"].replace("white", 1)

In [16]:
#Criando treino e test
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split (x, y, test_size = 0.3)

(1950, 12)

In [18]:
from sklearn.ensemble import ExtraTreesClassifier
#Criando modelo
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo o resultado
resultado = modelo.score(x_teste, y_teste)
print("Probabilidade: " , resultado)

Probabilidade:  0.9969230769230769

In [19]:
y_teste[500:505]

3095    1
6465    1
2979    1
1052    0
1956    1
Name: style, dtype: int64

In [20]:
x_teste[500:505]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3095,6.7,0.620,0.24,1.1,0.039,6.0,62.0,0.99340,3.41,0.32,10.4,5
6465,5.7,0.410,0.21,1.9,0.048,30.0,112.0,0.99138,3.29,0.55,11.2,6
2979,6.9,0.380,0.32,8.5,0.044,36.0,152.0,0.99320,3.38,0.35,12.0,7
1052,5.6,0.605,0.05,2.4,0.073,19.0,25.0,0.99258,3.56,0.55,12.9,5
1956,6.1,0.360,0.33,1.1,0.050,24.0,169.0,0.99270,3.15,0.78,9.5,6

In [21]:
#Demonstrar a a eficiencia da IA
previsao = modelo.predict(x_teste[500:505])
print(previsao)

[1 1 1 0 1]